spring:
  ai:
    zhipuai:
      # api-key 使用你自己申请的进行替换；如果为了安全考虑，可以通过启动参数进行设置
      api-key: ${zhipuai-api-key}
      chat:
        options:
          model: GLM-4-Flash

# Spring Boot 全局编码配置（YAML格式）
server:
  servlet:
    encoding:
      enabled: true # 启用HTTP编码支持
      force: true        # 强制Servlet层使用指定编码
      charset: UTF-8 # 核心编码格式（解决乱码的关键）